from lang_helper_by_delica.FrenchAdjective import FrenchAdjective

absorbe_adj = FrenchAdjective("absorbé", english_def="absorbed/engrossed in something")
accueillant_adj = FrenchAdjective("accueillant", english_def="welcoming")
affectueux_adj = FrenchAdjective("affectueux", english_def="affectionate")
age_adj = FrenchAdjective("âgé", english_def="old/elderly/aged")
agressif_adj = FrenchAdjective("agressif", english_def="aggressive")
aimable_adj = FrenchAdjective("aimable", english_def="nice/kind/friendly")
allemand_adj = FrenchAdjective("Allemand", english_def="german")
altruiste_adj = FrenchAdjective("altruiste", english_def="altruistic")
americain_adj = FrenchAdjective("américain", english_def="American")
amical_adj = FrenchAdjective("amical", english_def="friendly")
ambitieux_adj = FrenchAdjective("ambitieux", english_def="ambitious")
anglais_adj = FrenchAdjective("Anglais", english_def="english")
anxieux_adj = FrenchAdjective("anxieux", english_def="anxious")
apaisant_adj = FrenchAdjective("apaisant", english_def="soothing/calming")
apathique_adj = FrenchAdjective("apathique", english_def="apathetic")
applique_adj = FrenchAdjective("appliqué", english_def="diligent/hard-working")
arrogant_adj = FrenchAdjective("arrogant", english_def="arrogant")
asocial_adj = FrenchAdjective("asocial", english_def="asocial")
attentif_adj = FrenchAdjective("attentif", english_def="attentive")
attentionne_adj = FrenchAdjective("attentionné", english_def="thoughtful/caring")
audacieux_adj = FrenchAdjective("audacieux", english_def="audacious/bold/daring")
australien_adj = FrenchAdjective("australien", english_def="Australian")
autonome_adj = FrenchAdjective("autonome", english_def="autonomous/independent")
autoritaire_adj = FrenchAdjective("autoritaire", english_def="authoritarian/bossy/domineering")
avare_adj = FrenchAdjective("avare", english_def="stingy/miserly")
bavard_adj = FrenchAdjective("bavard", english_def="chatty/talkative")
beau_adj = FrenchAdjective("beau", english_def="beautiful/handsome", before_noun=True, fem_sing_form="belle",
                           masc_sing_before_vowel="bel")
belge_adj = FrenchAdjective("belge", english_def="Belgian")
bete_adj = FrenchAdjective("bête", english_def="silly/stupid/foolish")
bleu_adj = FrenchAdjective("bleu", english_def="blue")
blond_adj = FrenchAdjective("blond", english_def="blond")
brave_adj = FrenchAdjective("brave", english_def="brave/courageous")
bresilien_adj = FrenchAdjective("brésilien", english_def="Brazilian")
brillant_adj = FrenchAdjective("brillant", english_def="bright/shiny/brilliant")
bruyant_adj = FrenchAdjective("bruyant", english_def="loud/noisy")
celibataire_adj = FrenchAdjective("célibataire", english_def="single")
decourage_adj = FrenchAdjective("découragé", english_def="discouraged/disheartened")
dependant_adj = FrenchAdjective("dépendant", english_def="dependent")
detendu_adj = FrenchAdjective("détendu", english_def="relaxed/calm")
distrait_adj = FrenchAdjective("distrait", english_def="distracted")
doux_adj = FrenchAdjective("doux", english_def="soft", fem_sing_form="douce")
espagnol_adj = FrenchAdjective("espagnol", english_def="Spanish")
fatigue_adj = FrenchAdjective("fatigué", english_def="tired")
ferme_adj = FrenchAdjective("fermé", english_def="closed")
francais_adj = FrenchAdjective("français", english_def="French")
grand_adj = FrenchAdjective("grand", english_def="big/tall/great(when describing people)", before_noun=True)
grec_adj = FrenchAdjective("grec", english_def="Greek", fem_sing_form="grecque")
gris_adj = FrenchAdjective("gris", english_def="grey/gray")
gros_adj = FrenchAdjective("gros", english_def="big/large/thick", before_noun=True, fem_sing_form="grosse")
hollandais_adj = FrenchAdjective("hollandais", english_def="Dutch")
humble_adj = FrenchAdjective("humble", english_def="humble/modest")
indifferent_adj = FrenchAdjective("indifférent", english_def="indifferent")
italien_adj = FrenchAdjective("italien", english_def="Italian")
jaloux_adj = FrenchAdjective("jaloux", english_def="jealous")
japonais_adj = FrenchAdjective("japonais", english_def="Japanese")
jeune_adj = FrenchAdjective("jeune", english_def="young", before_noun=True)
jovial_adj = FrenchAdjective("jovial", english_def="cheerful")
joyeux_adj = FrenchAdjective("joyeux", english_def="joyful/happy")
juste_adj = FrenchAdjective("juste", english_def="fair/just")
lache_adj = FrenchAdjective("lâche", english_def="cowardly")
laid_adj = FrenchAdjective("laid", english_def="ugly")
leader_adj = FrenchAdjective("leader", english_def="leader/leading", is_invariable=True, is_loan_word=True)
lent_adj = FrenchAdjective("lent", english_def="lented")
libre_adj = FrenchAdjective("libre", english_def="free")
logique_adj = FrenchAdjective("logique", english_def="logique")

loyal_adj = FrenchAdjective("loyal", english_def="loyal")
marie_adj = FrenchAdjective("marié", english_def="married")
mince_adj = FrenchAdjective("mince", english_def="thin")
muscle_adj = FrenchAdjective("musclé", english_def="muscular")
naif_adj = FrenchAdjective("naïf", english_def="naive/gullible/innocent")
narcissique_adj = FrenchAdjective("narcissique", english_def="narcissistic")
negatif_adj = FrenchAdjective("négatif",english_def="negative")
negligent_adj = FrenchAdjective("négligent", english_def="negligent/careless")
nerveux_adj = FrenchAdjective("nerveux", english_def="nervous")
niais_adj = FrenchAdjective("niais", english_def="silly/simple/stupid/foolish")
nihiliste_adj = FrenchAdjective("nihiliste", english_def="nihilistic")
noir_adj = FrenchAdjective("noir", english_def="black")
nonchalant_adj = FrenchAdjective("nonchalant", english_def="nonchalant")
normal_adj = FrenchAdjective("normal", english_def="normal/ordinary/average")
occupe_adj = FrenchAdjective("occupé", english_def="busy")
paresseux_adj = FrenchAdjective("paresseux", english_def="lazy")
petit_adj = FrenchAdjective("petit", english_def="small/little/short", before_noun=True)
portugais_adj = FrenchAdjective("portugais", english_def="Portuguese")
pret_adj = FrenchAdjective("prêt", english_def="ready")
realiste_adj = FrenchAdjective("réaliste", english_def="realistic")
reserve_adj = FrenchAdjective("réservé", english_def="reserved/shy")
roux_adj = FrenchAdjective("roux", english_def="red-haired", fem_sing_form="rousse")
russe_adj = FrenchAdjective("russe", english_def="Russian")
seul_adj = FrenchAdjective("seul", english_def="alone/only/lonely")
silencieux_adj = FrenchAdjective("silencieux", english_def="silent/quiet")
suedois_adj = FrenchAdjective("suédois", english_def="Swedish")
taquin_adj = FrenchAdjective("taquin", english_def="teasing")
tatoue_adj = FrenchAdjective("tatoué", english_def="tattooed")
tenace_adj = FrenchAdjective("tenace", english_def="tenacious")
tendre_adj = FrenchAdjective("tendre", english_def="tender/loving")
tetu_adj = FrenchAdjective("têtu", english_def="stubborn")
timide_adj = FrenchAdjective("timide", english_def="timid/shy")
tolerant_adj = FrenchAdjective("tolérant", english_def="tolerant")
torture_adj = FrenchAdjective("torturé", english_def="tortured/tormented")
traitre_adj = FrenchAdjective("traître", english_def="traitor/treacherous")
tranquille_adj = FrenchAdjective("tranquille", english_def="quiet/calm/peaceful/tranquil")
travailleur_adj = FrenchAdjective("travailleur", english_def="hard-working")
tricheur_adj = FrenchAdjective("tricheur", english_def="cheating/deceitful")
triste_adj = FrenchAdjective("triste", english_def="sad")
utopiste_adj = FrenchAdjective("utopiste", english_def="utopian")
vaniteux_adj = FrenchAdjective("vaniteux", english_def="vain")
vantard_adj = FrenchAdjective("vantard", english_def="boastful")
vicieux_adj = FrenchAdjective("vicieux", english_def="vicious")
violent_adj = FrenchAdjective("violent", english_def="violent")
virulent_adj = FrenchAdjective("virulent", english_def="virulent")
vieux_adj = FrenchAdjective("vieux", english_def="old", before_noun=True, fem_sing_form="vieille",
                            masc_sing_before_vowel="vieil")

bleu_adj.print_forms()