from lang_helper_by_delica.FrenchVerbRegCER import FrenchVerbRegCER
from lang_helper_by_delica.FrenchVerbRegELER import FrenchVerbRegELER
from lang_helper_by_delica.FrenchVerbRegGER import FrenchVerbRegGER
from lang_helper_by_delica.FrenchVerbRegEConsER import FrenchVerbRegEConsER
from lang_helper_by_delica.FrenchVerbRegER import FrenchVerbRegER
from lang_helper_by_delica.FrenchVerbRegIR import FrenchVerbRegIR
from lang_helper_by_delica.FrenchVerbRegRE import FrenchVerbRegRE


french_reg_er_verbs = [FrenchVerbRegRE("accepter", "to accept"),
                       FrenchVerbRegRE("aimer", "to like/love"),
                       FrenchVerbRegRE("annuler", "to cancel"),
                       FrenchVerbRegRE("apporter", "to bring"),
                       FrenchVerbRegRE("attraper", "to catch"),
                       FrenchVerbRegRE("augmenter", "to increase"),
                       FrenchVerbRegRE("bavarder", "to chat"),
                       FrenchVerbRegRE("casser", "to break"),
                       FrenchVerbRegRE("chanter", "to sing"),
                       FrenchVerbRegRE("chercher", "to look for"),
                       FrenchVerbRegRE("commander", "to order"),
                       FrenchVerbRegRE("danser", "to dance"),
                       FrenchVerbRegRE("déjeuner", "to have lunch"),
                       FrenchVerbRegRE("demander", "to ask"),
                       FrenchVerbRegRE("dessiner", "to draw"),
                       FrenchVerbRegRE("donner", "to give"),
                       FrenchVerbRegRE("emprunter", "to borrow"),
                       FrenchVerbRegRE("étudier", "to study"),
                       FrenchVerbRegRE("exprimer", "to express"),
                       FrenchVerbRegRE("gagner", "to win"),
                       FrenchVerbRegRE("habiter", "to live"),
                       FrenchVerbRegRE("laver", "to wash"),
                       FrenchVerbRegRE("mériter", "to deserve"),
                       FrenchVerbRegRE("oublier", "to forget"),
                       FrenchVerbRegRE("porter", "to carry"),
                       FrenchVerbRegRE("prêter", "to lend"),
                       FrenchVerbRegRE("refuser", "to refuse"),
                       FrenchVerbRegRE("regarder", "to watch"),
                       FrenchVerbRegRE("saluer", "to greet"),
                       FrenchVerbRegRE("sauter", "to jump"),
                       FrenchVerbRegRE("tomber", "to fall"),
                       FrenchVerbRegRE("travailler", "to work"),
                       FrenchVerbRegRE("visiter", "to visit (physical location)"),
                       FrenchVerbRegRE("exprimer", "to express"),
                       FrenchVerbRegRE("gagner", "to win"),
                       FrenchVerbRegRE("habiter", "to live"),
                       FrenchVerbRegRE("laver", "to wash"),
                       FrenchVerbRegRE("manger", "to eat"),
                       ]



french_reg_cer_verbs = [FrenchVerbRegCER("annoncer", "to announce"),
                        FrenchVerbRegCER("avancer", "to advance/move forward"),
                        FrenchVerbRegCER("balancer", "to swing"),
                        FrenchVerbRegCER("commencer", "to start"),
                        FrenchVerbRegCER("défoncer", "to smash in"),
                        FrenchVerbRegCER("déplacer", "to move"),
                        FrenchVerbRegCER("devancer", "to get ahead of"),
                        FrenchVerbRegCER("effacer", "to erase"),
                        FrenchVerbRegCER("épicer", "to spice"),
                        FrenchVerbRegCER("exercer", "to wield/exercise"),
                        FrenchVerbRegCER("financer", "to finance"),
                        FrenchVerbRegCER("grimacer", "to grimace/wince/make faces"),
                        FrenchVerbRegCER("influencer", "to influence"),
                        FrenchVerbRegCER("lacer", "to lace up/tie"),
                        FrenchVerbRegCER("menacer", "to threaten"),
                        FrenchVerbRegCER("percer", "to pierce"),
                        FrenchVerbRegCER("placer", "to place"),
                        FrenchVerbRegCER("poncer", "to sand"),
                        FrenchVerbRegCER("prononcer", "to pronounce"),
                        FrenchVerbRegCER("remplacer", "to replace"),
                        FrenchVerbRegCER("renoncer", "to give up"),
                        ]

french_reg_ger_verbs = [FrenchVerbRegGER("bouger", "to move"),
                        FrenchVerbRegGER("changer", "to change"),
                        FrenchVerbRegGER("corriger", "to correct"),
                        FrenchVerbRegGER("dégager", "to clear/release/free"),
                        FrenchVerbRegGER("déménager", "to move (change homes)"),
                        FrenchVerbRegGER("encourager", "to encourage"),
                        FrenchVerbRegGER("exiger", "to demand/require"),
                        FrenchVerbRegGER("héberger", "to host/accommodate"),
                        FrenchVerbRegGER("manger", "to eat"),
                        FrenchVerbRegGER("mélanger", "to mix"),
                        FrenchVerbRegGER("nager", "to swim"),
                        FrenchVerbRegGER("négliger", "to neglect"),
                        FrenchVerbRegGER("partager", "to share"),
                        FrenchVerbRegGER("plonger", "to dive"),
                        FrenchVerbRegGER("protéger", "to protect"),
                        FrenchVerbRegGER("ranger", "to put away/tidy"),
                        FrenchVerbRegGER("venger", "to avenge"),
                        FrenchVerbRegGER("voyager", "to travel"),]

french_reg_eler_verbs = [FrenchVerbRegELER("appeler", "to call"),
                         FrenchVerbRegELER("épeler", "to spell"),
                         FrenchVerbRegELER("ensorceler", "to bewitch"),
                         FrenchVerbRegELER("étinceler", "to sparkle/glitter"),
                         FrenchVerbRegELER("ficeler", "to tie/bind"),
                         FrenchVerbRegELER("niveler", "to level"),
                         FrenchVerbRegELER("rappeler", "to remind/call back/recall"),
                         FrenchVerbRegELER("renouveler", "to renew"),]

french_reg_e_cons_er_verbs = [FrenchVerbRegEConsER("acheter", "to buy"),
                              FrenchVerbRegEConsER("achever", "to complete"),
                              FrenchVerbRegEConsER("céder", "to yield"),
                              FrenchVerbRegEConsER("célébrer", "to celebrate"),
                              FrenchVerbRegEConsER("considérer", "to consider"),
                              FrenchVerbRegEConsER("déléguer", "to delegate"),
                              FrenchVerbRegEConsER("emmener", "to take along/escort"),
                              FrenchVerbRegEConsER("enlever", "to remove"),
                              FrenchVerbRegEConsER("espérer", "to hope"),
                              FrenchVerbRegEConsER("exagérer", "to exaggerate"),
                              FrenchVerbRegEConsER("gérer", "to manage"),
                              FrenchVerbRegEConsER("lécher", "to lich"),
                              FrenchVerbRegEConsER("lever", "to raise"),
                              FrenchVerbRegEConsER("mener", "to lead/carry out"),
                              FrenchVerbRegEConsER("peser", "to weigh"),
                              FrenchVerbRegEConsER("posséder", "to possess/own"),
                              FrenchVerbRegEConsER("préférer", "to prefer"),
                              FrenchVerbRegEConsER("révéler", "to reveal"),
                              ]