from lang_helper_by_delica.FrenchVerbRegCER import FrenchVerbRegCER
from lang_helper_by_delica.FrenchVerbRegER import FrenchVerbRegER
from lang_helper_by_delica.FrenchVerbRegIR import FrenchVerbRegIR
from lang_helper_by_delica.FrenchVerbRegRE import FrenchVerbRegRE


french_reg_er_verbs = [FrenchVerbRegRE("accepter", "to accept"),
                       FrenchVerbRegRE("aimer", "to like/love"),
                       FrenchVerbRegRE("annuler", "to cancel"),
                       FrenchVerbRegRE("apporter", "to bring"),
                       FrenchVerbRegRE("attraper", "to catch"),
                       FrenchVerbRegRE("augmenter", "to increase"),
                       FrenchVerbRegRE("bavarder", "to chat"),
                       FrenchVerbRegRE("casser", "to break"),
                       FrenchVerbRegRE("chanter", "to sing"),
                       FrenchVerbRegRE("chercher", "to look for"),
                       FrenchVerbRegRE("commander", "to order"),
                       FrenchVerbRegRE("danser", "to dance"),
                       FrenchVerbRegRE("déjeuner", "to have lunch"),
                       FrenchVerbRegRE("demander", "to ask"),
                       FrenchVerbRegRE("dessiner", "to draw"),
                       FrenchVerbRegRE("donner", "to give"),
                       FrenchVerbRegRE("emprunter", "to borrow"),
                       FrenchVerbRegRE("enlever", "to remove"),
                       FrenchVerbRegRE("étudier", "to study"),
                       FrenchVerbRegRE("exprimer", "to express"),
                       FrenchVerbRegRE("gagner", "to win"),
                       FrenchVerbRegRE("habiter", "to live"),
                       FrenchVerbRegRE("laver", "to wash"),
                       FrenchVerbRegRE("manger", "to eat"),
                       FrenchVerbRegRE("mériter", "to deserve"),
                       FrenchVerbRegRE("oublier", "to forget"),
                       FrenchVerbRegRE("porter", "to carry"),
                       FrenchVerbRegRE("prêter", "to lend"),
                       FrenchVerbRegRE("refuser", "to refuse"),
                       FrenchVerbRegRE("regarder", "to watch"),
                       FrenchVerbRegRE("saluer", "to greet"),
                       FrenchVerbRegRE("sauter", "to jump"),
                       FrenchVerbRegRE("tomber", "to fall"),
                       FrenchVerbRegRE("travailler", "to work"),
                       FrenchVerbRegRE("visiter", "to visit (physical location)"),
                       FrenchVerbRegRE("exprimer", "to express"),
                       FrenchVerbRegRE("gagner", "to win"),
                       FrenchVerbRegRE("habiter", "to live"),
                       FrenchVerbRegRE("laver", "to wash"),
                       FrenchVerbRegRE("manger", "to eat"),
                       ]



french_reg_cer_verbs = [FrenchVerbRegCER("annoncer", "to announce"),
                        FrenchVerbRegCER("avancer", "to advance/move forward"),
                        FrenchVerbRegCER("balancer", "to swing"),
                        FrenchVerbRegCER("commencer", "to start"),
                        FrenchVerbRegCER("défoncer", "to smash in"),
                        FrenchVerbRegCER("déplacer", "to move"),
                        FrenchVerbRegCER("devancer", "to get ahead of"),
                        FrenchVerbRegCER("effacer", "to erase"),
                        FrenchVerbRegCER("épicer", "to spice"),
                        FrenchVerbRegCER("financer", "to finance"),
                        FrenchVerbRegCER("grimacer", "to grimace/wince/make faces"),
                        FrenchVerbRegCER("influencer", "to influence"),
                        FrenchVerbRegCER("lacer", "to lace up/tie"),
                        FrenchVerbRegCER("menacer", "to threaten"),
                        FrenchVerbRegCER("percer", "to pierce"),
                        FrenchVerbRegCER("placer", "to place"),
                        FrenchVerbRegCER("poncer", "to sand"),
                        FrenchVerbRegCER("prononcer", "to pronounce"),
                        FrenchVerbRegCER("remplacer", "to replace"),
                        FrenchVerbRegCER("renoncer", "to give up"),
                        ]