from lang_helper_by_delica.FrenchAdjective import FrenchAdjective

absorbe_adj = FrenchAdjective("absorbé", english_def="absorbed/engrossed in something")
accueillant_adj = FrenchAdjective("accueillant", english_def="welcoming")
affectueux_adj = FrenchAdjective("affectueux", english_def="affectionate")
agressif_adj = FrenchAdjective("agressif", english_def="aggressive")
aimable_adj = FrenchAdjective("aimable", english_def="nice/kind/friendly")
altruiste_adj = FrenchAdjective("altruiste", english_def="altruistic")
amical_adj = FrenchAdjective("amical", english_def="friendly")
ambitieux_adj = FrenchAdjective("ambitieux", english_def="ambitious")
anxieux_adj = FrenchAdjective("anxieux", english_def="anxious")
apaisant_adj = FrenchAdjective("apaisant", english_def="soothing/calming")
apathique_adj = FrenchAdjective("apathique", english_def="apathetic")
applique_adj = FrenchAdjective("appliqué", english_def="diligent/hard-working")
arrogant_adj = FrenchAdjective("arrogant", english_def="arrogant")
asocial_adj = FrenchAdjective("asocial", english_def="asocial")
attentif_adj = FrenchAdjective("attentif", english_def="attentive")
attentionne_adj = FrenchAdjective("attentionné", english_def="thoughtful/caring")
audacieux_adj = FrenchAdjective("audacieux", english_def="audacious/bold/daring")
autonome_adj = FrenchAdjective("autonome", english_def="autonomous/independent")
autoritaire_adj = FrenchAdjective("autoritaire", english_def="authoritarian/bossy/domineering")
avare_adj = FrenchAdjective("avare", english_def="stingy/miserly")
bavard_adj = FrenchAdjective("bavard", english_def="chatty/talkative")
bete_adj = FrenchAdjective("bête", english_def="silly/stupid/foolish")
brave_adj = FrenchAdjective("brave", english_def="brave/courageous")
brillant_adj = FrenchAdjective("brillant", english_def="bright/shiny/brilliant")
bruyant_adj = FrenchAdjective("bruyant", english_def="loud/noisy")
decourage_adj = FrenchAdjective("découragé", english_def="discouraged/disheartened")
dependant_adj = FrenchAdjective("dépendant", english_def="dependent")
detendu_adj = FrenchAdjective("détendu", english_def="relaxed/calm")
distrait_adj = FrenchAdjective("distrait", english_def="distracted")
doux_adj = FrenchAdjective("doux", english_def="soft", fem_sing_form="douce")
humble_adj = FrenchAdjective("humble", english_def="humble/modest")
indifferent_adj = FrenchAdjective("indifférent", english_def="indifferent")
jaloux_adj = FrenchAdjective("jaloux", english_def="jealous")
jeune_adj = FrenchAdjective("jeune", english_def="young", before_verb=True)
jovial_adj = FrenchAdjective("jovial", english_def="cheerful")
joyeux_adj = FrenchAdjective("joyeux", english_def="joyful/happy")
juste_adj = FrenchAdjective("juste", english_def="fair/just")
realiste_adj = FrenchAdjective("réaliste", english_def="realistic")
reserve_adj = FrenchAdjective("réservé", english_def="reserved/shy")
silencieux_adj = FrenchAdjective("silencieux", english_def="silent/quiet")
taquin_adj = FrenchAdjective("taquin", english_def="teasing")
tenace_adj = FrenchAdjective("tenace", english_def="tenacious")
tendre_adj = FrenchAdjective("tendre", english_def="tender/loving")
tetu_adj = FrenchAdjective("têtu", english_def="stubborn")
timide_adj = FrenchAdjective("timide", english_def="timid/shy")
tolerant_adj = FrenchAdjective("tolérant", english_def="tolerant")
triste_adj = FrenchAdjective("triste", english_def="sad")
utopiste_adj = FrenchAdjective("utopiste", english_def="utopian")
vaniteux_adj = FrenchAdjective("vaniteux", english_def="vain")
vantard_adj = FrenchAdjective("vantard", english_def="boastful")
vicieux_adj = FrenchAdjective("vicieux", english_def="vicious")
violent_adj = FrenchAdjective("violent", english_def="violent")
virulent_adj = FrenchAdjective("virulent", english_def="virulent")

jeune_adj.print_forms()