

FIRST_PERSON = 1
SECOND_PERSON = 2
THIRD_PERSON = 3
PERSON_OPTIONS = [FIRST_PERSON, SECOND_PERSON, THIRD_PERSON]

FEMININE = "f"
MASCULINE = "m"
NO_GENDER = "n"
BOTH_GENDERS = "f/m"
WORD_GENDERS = [FEMININE, MASCULINE, NO_GENDER, BOTH_GENDERS]
FRENCH_WORD_GENDERS = [FEMININE, MASCULINE, BOTH_GENDERS]
SPANISH_WORD_GENDERS = [FEMININE, MASCULINE, BOTH_GENDERS]
FRENCH_VOWELS = ["a", "e", "é", "è", "i", "o", "u"]

EARLY_MORNING = "early morning"
MID_MORNING = "mid morning"
LATE_MORNING = "late morning"
MORNING = "morning"
MORNING_TIMES = [MORNING, EARLY_MORNING, MID_MORNING, LATE_MORNING]

EARLY_AFTERNOON = "early afternoon"
MID_AFTERNOON = "mid afternoon"
LATE_AFTERNOON = "late afternoon"
AFTERNOON = "afternoon"
AFTERNOON_TIMES = [AFTERNOON, EARLY_AFTERNOON, MID_AFTERNOON, LATE_AFTERNOON]

EARLY_EVENING = "early evening"
MID_EVENING = "mid evening"
LATE_EVENING = "late evening"
EVENING = "evening"
EVENING_TIMES = [EVENING, EARLY_EVENING, MID_EVENING, LATE_EVENING]

ALL_TIMES = MORNING_TIMES + AFTERNOON_TIMES + EVENING_TIMES