

FIRST_PERSON = 1
SECOND_PERSON = 2
THIRD_PERSON = 3
PERSON_OPTIONS = [FIRST_PERSON, SECOND_PERSON, THIRD_PERSON]

FEMININE = "f"
MASCULINE = "m"
NO_GENDER = "n"
BOTH_GENDERS = "f/m"
WORD_GENDERS = [FEMININE, MASCULINE, NO_GENDER, BOTH_GENDERS]
FRENCH_WORD_GENDERS = [FEMININE, MASCULINE, BOTH_GENDERS]
SPANISH_WORD_GENDERS = [FEMININE, MASCULINE, BOTH_GENDERS]
FRENCH_VOWELS = ["a", "e", "é", "è", "i", "o", "u"]