from lang_helper_by_delica.SpanishAdjective import SpanishAdjective

agobiado_adj = SpanishAdjective("agobiado", english_def="overwhelmed", uses_ser=False)
ansioso_adj = SpanishAdjective("ansioso", english_def="anxious", uses_ser=False)
autoritario_adj = SpanishAdjective("autoritario",english_def="strict/authoritarian")
carinoso_adj = SpanishAdjective("cariñoso",english_def="affectionate")
casado_adj = SpanishAdjective("casado", english_def="married")
celoso_adj = SpanishAdjective("celoso", english_def="jealous")
cuidadoso_adj = SpanishAdjective("cuidadoso", english_def="cautious/careful")
deprimido_adj = SpanishAdjective("deprimido", english_def="depressed", uses_ser=False)
disgustado_adj = SpanishAdjective("disgustado", english_def="upset", uses_ser=False)
emocionado_adj = SpanishAdjective("emocionado", english_def="excited", uses_ser=False)
divorciado_adj = SpanishAdjective("divorciado", english_def="divorced")
falso_adj = SpanishAdjective("falso", english_def="false/insincere")
gracioso_adj = SpanishAdjective("gracioso", english_def="funny")
inseguro_adj = SpanishAdjective("inseguro", english_def="insecure")
inmaduro_adj = SpanishAdjective("inmaduro", english_def="immature")
maduro_adj = SpanishAdjective("maduro", english_def="mature")
mentiroso_adj = SpanishAdjective("mentiroso", english_def="lying")
orgulloso_adj = SpanishAdjective("orgulloso", english_def="proud")
permisivo_adj = SpanishAdjective("permisivo", english_def="permissive")
preocupado_adj = SpanishAdjective("preocupado", english_def="worried", uses_ser=False)
seguro_adj = SpanishAdjective("seguro", english_def="secure")
sensato_adj = SpanishAdjective("sensato", english_def="sensible")
sensible_adj = SpanishAdjective("sensible", english_def="sensitive")
separado_adj = SpanishAdjective("separado", english_def="separated")
solo_adj = SpanishAdjective("solo", english_def="alone/lonely", uses_ser=False)
soltero_adj = SpanishAdjective("soltero", english_def="single")
tacano_adj = SpanishAdjective("tacaño", english_def="stingy/cheap")
timido_adj = SpanishAdjective("tímido", english_def="timid/shy")
tradicional_adj = SpanishAdjective("tradicional", english_def="traditional")
tranquilo_adj = SpanishAdjective("tranquilo", english_def="calm", uses_ser=False)
viudo_adj = SpanishAdjective("viudo", english_def="widowed")


autoritario_adj.print_forms()